server:
  port: 8080

spring:
  application:
    name: ShowHub

  datasource:
    url: jdbc:postgresql://localhost:5432/hub_api
    username: ltt4456
    password: password

  jpa:
    show-sql: true

  web:
    error:
      include-message: always

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 100000
    refreshTokenExpiration: 604800

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  base-url: http://localhost:8080
  email:
    verification-expiry-hours: 24
    reset-expiry-minutes: 15

